Lotto game PR 요청합니다.
cleancode-practice-study/java-practice-lotto pull request #4
Opened 2022-02-23 09:51 UTC by Egenieee

아직 MVC 패턴을 정확이 어떤 식으로 적용해야 하는 지 잘 모르겠지만, 할 수 있는 만큼 구현해봤습니다! 구현 하면서 계속 고민 했던 부분이 **Controller 와 Model의 경계** 라고 할까요,,? Controller가 하는 일이 어디까지 커버를 해야하는 지 감이 제일 안오더라구요,, 

제가 알기론 Controller 은 가운데서 값을 받아서 넘겨주는 역할만 하는 걸로 알고 있는데, 제가 짠 코드는 대부분의 로직이 Controller에 있어서 이걸 어떻게 Domain으로 옮겨야 하는 지 잘 모르겠습니다 😅 

Controller에서 view나 다른 Lotto, WinningLotto 객체를 다 사용하긴 했는데 이렇게 하는 게 아닌 거 같아요 하하..
일단 그런 부분은 피드백을 받아보고 싶기도 하고 더 이상 refactoring을 어떻게 해야할 지 모르겠어서 여기서 스탑하고 pr요청합니다..!

바쁘실텐데 감사합니다 😭

2022-02-23 16:31 UTC, gch01410 requested changes
잘했는데?? ㅋㅋㅋ
우선 MVC 패턴 관련해서만 리뷰남겼어!
몇개 안되니까 확인해보고! ㅋㅋ
테스트 코드도 작성해서 다시 요청해줘

2022-02-23 16:31 UTC, ghost commented on src/main/java/controller/Controller.java
> +        System.out.println();
출력은 View영역에서 하도록 변경해보자!

2022-02-23 16:31 UTC, ghost commented on src/main/java/domain/Lotto.java
> +		System.out.println(numbers);
Lotto객체는 Domain영역에 속해! 왜 Domain영역에 속하는지 고민해봐!
그리고 출력하는 로직은 모두 컨트롤러를 통해 View에서 수행되도록 변경해보자.
Domain영역에서 출력에 관한 로직을 모두 없애봐!

2022-02-23 16:31 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +            InputView.checkValidWinningLottoNumber(isValid);
이 로직은 입력을 받는게 아니고 검증만 하고 있어서 View영역이 아니라 다른곳에 있어도 괜찮지않을까?

2022-02-27 05:02 UTC, gch01410 requested changes
테스트 코드 꼼꼼하게 작성 잘했어! 👍 
다만 컨트롤러가 많은 역할을 하고 있는것 같네
컨트롤러는 model영역과 view영역 사이에서 데이터를 전달해주는 역할만 하도록 변경해봐! 
게임진행은 model영역에서 담당하고 게임진행에 필요한 값을 컨트롤러를 통해 view에서 전달도록 구현하면 될 것 같아

2022-02-27 05:02 UTC, ghost commented on src/main/java/controller/Controller.java
> +        return lottoes;
메서드안의 지역변수로 선언 👍

2022-02-27 05:02 UTC, ghost commented on src/main/java/controller/Controller.java
> +        }
구입한 로또 개수만큼 로또 객체를 생성하는 로직은 게임진행에 포함되는 로직( = 비즈니스 로직)이 아닐까?
컨트롤러가 아니라 model영역에서 처리하도록 해보자

2022-02-27 05:02 UTC, ghost commented on src/main/java/controller/Controller.java
> +    private WinningLotto createWinningLotto() {
당첨 로또를 생성하는 로직도 비즈니스 로직에 해당하는것 같아~
컨트롤러가 아니라 model영역에서 처리하도록 해보자

2022-02-27 05:02 UTC, ghost commented on src/main/java/controller/Controller.java
> +    }
컨트롤러는 model영역으로부터 결과값을 받아서 View에 넘기는 역할만 하도록 변경해보자!

2022-02-27 05:02 UTC, ghost commented on src/test/java/domain/LottoTest.java
> +        lottoNumber.add(6);
Arrays.asList() 메서드를 사용해보자!

2022-02-27 05:02 UTC, ghost commented on src/test/java/domain/RankTest.java
> +        assertThat(rank.getWinningMoney()).isEqualTo(2000000000);
rank가 Enum의 어떤 값인지만 확인해도 충분할 것 같아!

2022-02-27 05:02 UTC, ghost commented on src/test/java/domain/CreateLottoNumberTest.java
> +        int lottoNumber = CreateLottoNumber.getRandomNumber(LOTTO_NUM_START_INCLUSIVE, LOTTO_NUM_END_INCLUSIVE);
CreateLottoNumber.getRandomNumber 메서드는 CreateLottoNumber.createLottosNumber 메서드에서만 사용되고 있으니 private으로 선언하는것이 맞아보여.
테스트 코드 작성을 위해서 public으로 선언한것이라면 좋지않은 방법이야. 테스트 코드 작성을 위해 프로덕션 코드(테스트 코드가 아닌 코드)를 변경하는것은 좋지않아!

private메서드를 호출하는 public메서드를 테스트하면서 private메서드의 로직도 테스트되도록 테스트 코드를 작성해보자!

2022-02-28 09:06 UTC, Egenieee commented
최대한 Controller는 전달자 역할만 하도록 수정해보았는데, 이렇게 되면 막상 문제가 Controller에 대한 Test 코드 작성을 어떤 식으로 해야할 지 모르겠더라구요,,! 아무리 생각해봐도 모르겠어서 일단은 피드백 받은 부분 수정해보고 푸쉬합니다!

2022-02-28 14:47 UTC, ghost requested changes
수고했어!
게임진행의 책임을 컨트롤러에서 GameHelper로 변경 👍 👍 
로직을 GameHelper로 분리하면서 테스트할 수 있는 메서드가 더 생겼어! 테스트코드 추가해보자!

2022-02-28 14:47 UTC, gch01410 commented on README.md
> +- domain.WinningLotto 기본 생성자를 추가할 수 없다.
이름 변경하면서 같이 변경된것 같네😄

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        helper.createLottoes(lottoes, lottoCount);
컨트롤러에서 선언과 초기화를 한 이유가 있을까??

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        domain.GameHelper helper = new domain.GameHelper();
GameHelper클래스를 인스턴스화해서 사용한 이유가 있을까??

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        double yield = helper.getYield(totalGetMoney, lottoes.size() * LOTTO_PRICE_PER_ONE);
수익률을 구하는 과정에서 총 상금을 계산해서 바로 사용해도 되지않을까?

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        List<Integer> winningResult = helper.getLottoResult(winningLotto, lottoes);
당첨결과를 List의 순서에 의존하지않고 받아보도록 할 수 있을까?

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/domain/CreateLottoNumber.java
> +public class CreateLottoNumber {
네이밍으로 `LottoNumberCreator` 가 더 적합해보여
클래스 이름은 보통 명사로 구성해!

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/domain/GameHelper.java
> +        return splitWinningNumbers.size() == 6;
6이 어떤 숫자인지 의미를 알기 어려울 수 있어
상수로 선언해서 이름으로 의미를 드러내주는게 좋아

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        int totalGetMoney = helper.getLottoTotalMoney(winningLotto, lottoes);
당첨금액을 구하는 과정에서 다시 당첨로또를 구하고 있어!
전에 구했던 당첨 결과를 이용해볼 수 있지않을까?

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/domain/GameHelper.java
> +    public Lotto createOneLotto() {
GameHelper의 메서드에서만 사용하고 있어서 private으로 선언하는게 맞는 것 같아!

2022-02-28 14:47 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        List<Lotto> lottoes = getLottoes();
Lotto 리스트를 일급컬렉션으로 만들어볼까?
https://jojoldu.tistory.com/412

2022-03-02 01:22 UTC, Egenieee commented
일급컬렉션을 써보는 건 처음이라 이렇게 하는게 맞는지 잘 모르겠지만,,^^ 일단 피드백 다 반영해서 수정하고 푸쉬합니다!

2022-03-02 12:40 UTC, gch01410 requested changes
조금만 더 수정해보자!

2022-03-02 12:40 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        double yield = GameHelper.getYield(lottoWinResult, lottoes.getLottoes().size() * LOTTO_PRICE_PER_ONE);
Lottoes가 로또 리스트를 갖고 있으니까 Lottoes가 로또개수를 반환할 수 있지않을까?

2022-03-02 12:40 UTC, gch01410 commented on src/main/java/domain/GameHelper.java
> +            lottoResult.put(rank, lottoResult.getOrDefault(rank, 0) + 1);
Lottes가 로또 리스트를 갖고 있으니 WinningLotto를 넘겨주면 Lttoes가 랭크를 구할 수 있지않을까?

2022-03-02 12:40 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        Map<Rank, Integer> lottoWinResult = GameHelper.getLottoWinResult(winningLotto, lottoes);
당첨결과도 일급컬렉션으로 만들어보자!

2022-03-02 12:40 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +    // 당첨 로또 받기
주석이 없어도 메서드 이름이나 변수명, 클래스 이름 등등.. 으로 로직을 이해할 수 있는게 좋아!
주석은 반드시 필요한 경우에만 사용해줘!

2022-03-03 13:12 UTC, gch01410 requested changes
일급컬렉션이 값을 갖고 있기때문에 컬렉션 값을 이용하는 로직을 일급컬렉션 안으로 넣을 수 있어!
일급컬렉션을 사용하면 좋은점에 대해서 알아보자!

2022-03-03 13:12 UTC, gch01410 commented on src/main/java/domain/GameHelper.java
> +        return lottoes.getLottoWinResult(lottoResult, winningLotto);
Lottes안에서 lottoResult 맵을 초기화해도 되지않을까?

2022-03-03 13:12 UTC, gch01410 commented on src/main/java/domain/GameHelper.java
> +    }
WinningResult가 로또결과를 알고 있으니 WinningResult가 총합을 구할 수 있지않을까?

2022-03-03 13:12 UTC, gch01410 commented on src/main/java/view/OutputView.java
> +        System.out.printf(LOTTO_FIRST_OUTPUT_MESSAGE, lottoWinResult.getLottoResult().get(Rank.FIRST));
중복을 제거해보자!
근데 WinningResult의 맵을 꺼내지않고도 값을 구할 수 있지않을까?

2022-03-08 00:39 UTC, gch01410 approved these changes
수고했어!

2022-03-08 03:43 UTC, merged